/*******************************************************************************
 * Copyright (c) 1998, 2019 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
 * or the Apache License, Version 2.0 which accompanies this distribution and
 * is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following
 * Secondary Licenses when the conditions for such availability set
 * forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
 * General Public License, version 2 with the GNU Classpath
 * Exception [1] and GNU General Public License, version 2 with the
 * OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

#ifndef J9CFG_H
#define J9CFG_H

/*
 * @ddr_namespace: map_to_type=J9BuildFlags
 * @ddr_options: valuesandbuildflags
 */

#ifdef __cplusplus
extern "C" {
#endif

#include "omrcfg.h"

#define J9_COPYRIGHT_STRING "(c) Copyright 1991, 2019 IBM Corp. and others."

#define EsVersionMajor 2
#define EsVersionMinor 90

#define EsExtraVersionString ""

#define JAVA_SPEC_VERSION 8

/*  Note: The following defines record flags used to build VM.  */
/*  Changing them here does not remove the feature and may cause linking problems. */

#define J9VM_ARCH_S390
#define J9VM_BUILD__SE6_PACKAGE
#define J9VM_BUILD_AUTOBUILD
#define J9VM_BUILD_DROP_TO_HURSLEY
#define J9VM_BUILD_DROP_TO_TORONTO
#define J9VM_BUILD_J2SE
#define J9VM_BUILD_JAVA60_26
#define J9VM_BUILD_JAVA6PROXY
#define J9VM_BUILD_JAVA7
#define J9VM_BUILD_JAVA70_27
#define J9VM_BUILD_JAVA8
#define J9VM_BUILD_OPENJ9
#define J9VM_BUILD_OPENJ9_JDK8
#define J9VM_BUILD_PRODUCT
#define J9VM_BUILD_STAGE_OTTAWA_VMLAB
#define J9VM_BUILD_UMA
#define J9VM_COMPILER_PROMOTION
#define J9VM_ENV_DATA64
#define J9VM_ENV_HAS_FPU
#define J9VM_ENV_SHARED_LIBS_CALLEE_GLOBAL_TABLE_SETUP
#define J9VM_ENV_SHARED_LIBS_USE_GLOBAL_TABLE
#define J9VM_GC_ADAPTIVE_TENURING
#define J9VM_GC_ALLOCATION_TAX
#define J9VM_GC_ARRAYLETS
#define J9VM_GC_BATCH_CLEAR_TLH
#define J9VM_GC_CLASSES_ON_HEAP
#define J9VM_GC_COMBINATION_SPEC
#define J9VM_GC_COMPRESSED_POINTERS
#define J9VM_GC_CONCURRENT_SWEEP
#define J9VM_GC_DEBUG_ASSERTS
#define J9VM_GC_DYNAMIC_CLASS_UNLOADING
#define J9VM_GC_DYNAMIC_NEW_SPACE_SIZING
#define J9VM_GC_FINALIZATION
#define J9VM_GC_FRAGMENTED_HEAP
#define J9VM_GC_GENERATIONAL
#define J9VM_GC_HEAP_CARD_TABLE
#define J9VM_GC_HYBRID_ARRAYLETS
#define J9VM_GC_IDLE_HEAP_MANAGER
#define J9VM_GC_INLINED_ALLOC_FIELDS
#define J9VM_GC_JNI_ARRAY_CACHE
#define J9VM_GC_LARGE_OBJECT_AREA
#define J9VM_GC_LEAF_BITS
#define J9VM_GC_MINIMUM_OBJECT_SIZE
#define J9VM_GC_MODRON_COMPACTION
#define J9VM_GC_MODRON_CONCURRENT_MARK
#define J9VM_GC_MODRON_GC
#define J9VM_GC_MODRON_SCAVENGER
#define J9VM_GC_MODRON_STANDARD
#define J9VM_GC_MODRON_TRACE
#define J9VM_GC_MODRON_VERBOSE
#define J9VM_GC_NON_ZERO_TLH
#define J9VM_GC_OBJECT_ACCESS_BARRIER
#define J9VM_GC_REALTIME
#define J9VM_GC_SEGREGATED_HEAP
#define J9VM_GC_STACCATO
#define J9VM_GC_SUBPOOLS_ALIAS
#define J9VM_GC_THREAD_LOCAL_HEAP
#define J9VM_GC_TILTED_NEW_SPACE
#define J9VM_GC_USE_INLINE_ALLOCATE
#define J9VM_GC_VLHGC
#define J9VM_INTERP_AOT_COMPILE_SUPPORT
#define J9VM_INTERP_AOT_RUNTIME_SUPPORT
#define J9VM_INTERP_ATOMIC_FREE_JNI
#define J9VM_INTERP_ATOMIC_FREE_JNI_USES_FLUSH
#define J9VM_INTERP_BYTECODE_PREVERIFICATION
#define J9VM_INTERP_BYTECODE_VERIFICATION
#define J9VM_INTERP_COMPRESSED_OBJECT_HEADER
#define J9VM_INTERP_CUSTOM_SPIN_OPTIONS
#define J9VM_INTERP_DEBUG_SUPPORT
#define J9VM_INTERP_ENABLE_JIT_ON_DESKTOP
#define J9VM_INTERP_FLAGS_IN_CLASS_SLOT
#define J9VM_INTERP_FLOAT_SUPPORT
#define J9VM_INTERP_GP_HANDLER
#define J9VM_INTERP_GROWABLE_STACKS
#define J9VM_INTERP_HOT_CODE_REPLACEMENT
#define J9VM_INTERP_JIT_ON_BY_DEFAULT
#define J9VM_INTERP_JNI_SUPPORT
#define J9VM_INTERP_NATIVE_SUPPORT
#define J9VM_INTERP_NEW_HEADER_SHAPE
#define J9VM_INTERP_PROFILING_BYTECODES
#define J9VM_INTERP_SIG_QUIT_THREAD
#define J9VM_INTERP_SMALL_MONITOR_SLOT
#define J9VM_INTERP_TWO_PASS_EXCLUSIVE
#define J9VM_INTERP_USE_UNSAFE_HELPER
#define J9VM_INTERP_VERBOSE
#define J9VM_IVE_JXE_FILE_RELOCATOR
#define J9VM_IVE_JXE_IN_PLACE_RELOCATOR
#define J9VM_IVE_JXE_NATIVES
#define J9VM_IVE_JXE_OERELOCATOR
#define J9VM_IVE_JXE_STREAMING_RELOCATOR
#define J9VM_IVE_ROM_IMAGE_HELPERS
#define J9VM_JIT_C_HELPERS
#define J9VM_JIT_CLASS_UNLOAD_RWMONITOR
#define J9VM_JIT_DYNAMIC_LOOP_TRANSFER
#define J9VM_JIT_FULL_SPEED_DEBUG
#define J9VM_JIT_GC_ON_RESOLVE_SUPPORT
#define J9VM_JIT_NEW_DUAL_HELPERS
#define J9VM_JIT_NEW_INSTANCE_PROTOTYPE
#define J9VM_JIT_RUNTIME_INSTRUMENTATION
#define J9VM_JIT_SUPPORTS_DIRECT_JNI
#define J9VM_JIT_TRANSACTION_DIAGNOSTIC_THREAD_BLOCK
#define J9VM_MATH_USE_DIV_REM
#define J9VM_OPT_ANNOTATIONS
#define J9VM_OPT_BIG_INTEGER
#define J9VM_OPT_DEBUG_INFO_SERVER
#define J9VM_OPT_DEBUG_JSR45_SUPPORT
#define J9VM_OPT_DEPRECATED_METHODS
#define J9VM_OPT_DYNAMIC_LOAD_SUPPORT
#define J9VM_OPT_FRAGMENT_RAM_CLASSES
#define J9VM_OPT_HARMONY
#define J9VM_OPT_ICBUILDER_SUPPORT
#define J9VM_OPT_INFO_SERVER
#define J9VM_OPT_INLINE_JSRS
#define J9VM_OPT_INVARIANT_INTERNING
#define J9VM_OPT_JVMTI
#define J9VM_OPT_JXE_LOAD_SUPPORT
#define J9VM_OPT_MEMORY_CHECK_SUPPORT
#define J9VM_OPT_METHOD_HANDLE
#define J9VM_OPT_MODULE
#define J9VM_OPT_MULTI_VM
#define J9VM_OPT_NEW_OBJECT_HASH
#define J9VM_OPT_NEW_ROM_CLASS_BUILDER
#define J9VM_OPT_REFLECT
#define J9VM_OPT_REMOTE_CONSOLE_SUPPORT
#define J9VM_OPT_ROM_IMAGE_SUPPORT
#define J9VM_OPT_SHARED_CLASSES
#define J9VM_OPT_SIDECAR
#define J9VM_OPT_SRP_AVL_TREE_SUPPORT
#define J9VM_OPT_STRING_COMPRESSION
#define J9VM_OPT_USE_FFI
#define J9VM_OPT_USE_FFI_ONLY
#define J9VM_OPT_VM_LOCAL_STORAGE
#define J9VM_OPT_ZIP_SUPPORT
#define J9VM_OPT_ZLIB_COMPRESSION
#define J9VM_OPT_ZLIB_SUPPORT
#define J9VM_PORT_OMRSIG_SUPPORT
#define J9VM_PORT_RUNTIME_INSTRUMENTATION
#define J9VM_PORT_SIGNAL_SUPPORT
#define J9VM_PROF_EVENT_REPORTING
#define J9VM_RAS_DUMP_AGENTS
#define J9VM_RAS_EYECATCHERS
#define J9VM_SIZE_OPTIMIZE_SEND_TARGETS
#define J9VM_THR_ASYNC_NAME_UPDATE
#define J9VM_THR_LOCK_NURSERY
#define J9VM_THR_LOCK_RESERVATION
#define J9VM_THR_PREEMPTIVE
#define J9VM_THR_SMART_DEFLATION

/* flags NOT used by this VM.  */
#undef J9VM_ARCH_AARCH64
#undef J9VM_ARCH_ARM
#undef J9VM_ARCH_POWER
#undef J9VM_ARCH_X86
#undef J9VM_BUILD__VS12_AND_HIGHER
#undef J9VM_BUILD_CMAKE
#undef J9VM_BUILD_DROP_TO_PHOENIX
#undef J9VM_BUILD_FIPS
#undef J9VM_BUILD_GC_CONTINUOUS
#undef J9VM_BUILD_J2ME
#undef J9VM_BUILD_J9VM_DOC
#undef J9VM_BUILD_JAVA5
#undef J9VM_BUILD_JAVA6
#undef J9VM_BUILD_JAVA7BASIC
#undef J9VM_BUILD_JAVA7RAW
#undef J9VM_BUILD_JAVA8RAW
#undef J9VM_BUILD_JAVA9
#undef J9VM_BUILD_OUNCEMAKE
#undef J9VM_BUILD_REALTIME
#undef J9VM_BUILD_STAGE_TORONTO_LAB
#undef J9VM_BUILD_VM_CONTINUOUS
#undef J9VM_DANGER_MEMLEAKS_BROKEN
#undef J9VM_ENV_ADVANCE_TOOLCHAIN
#undef J9VM_ENV_CALL_VIA_TABLE
#undef J9VM_ENV_DLPAR
#undef J9VM_ENV_GCC
#undef J9VM_ENV_LITTLE_ENDIAN
#undef J9VM_ENV_SSE2_SUPPORT_DETECTION
#undef J9VM_ENV_Z_TPF
#undef J9VM_GC_ALIGN_OBJECTS
#undef J9VM_GC_ALWAYS_CALL_OBJECT_ACCESS_BARRIER
#undef J9VM_GC_ALWAYS_CALL_WRITE_BARRIER
#undef J9VM_GC_COMPRESSED_POINTER_BARRIER
#undef J9VM_GC_NEW_SPINLOCK_SUPPORT
#undef J9VM_GC_STRICT_OMR
#undef J9VM_GC_SUBPOOLS
#undef J9VM_GC_TLH_PREFETCH_FTA
#undef J9VM_GC_VERIFY_ACCESS_BARRIER
#undef J9VM_INTERP_FLOATMATH_TRACING
#undef J9VM_INTERP_FLOATMATHLIB_TRACING
#undef J9VM_INTERP_MINIMAL_JCL
#undef J9VM_INTERP_MINIMAL_JNI
#undef J9VM_INTERP_ROMABLE_AOT_SUPPORT
#undef J9VM_INTERP_TRACING
#undef J9VM_INTERP_UPDATE_VMCTRACING
#undef J9VM_IVE_MEMORY_SPACE_HELPERS
#undef J9VM_IVE_RAW_BUILD
#undef J9VM_JIT_32BIT_USES64BIT_REGISTERS
#undef J9VM_JIT_FREE_SYSTEM_STACK_POINTER
#undef J9VM_JIT_IA32_FIXED_FRAME
#undef J9VM_JIT_MICRO_JIT
#undef J9VM_JIT_NATHELP_USES_CLASS_OBJECTS
#undef J9VM_JIT_NEEDS_TRAMPOLINES
#undef J9VM_JIT_ON_STACK_REPLACEMENT
#undef J9VM_JIT_REQUIRES_TRAP_HANDLER
#undef J9VM_JIT_SMALL
#undef J9VM_MATH_DIRECT_HELPERS
#undef J9VM_OPT_CUDA
#undef J9VM_OPT_DMA_NATIVES
#undef J9VM_OPT_FIPS
#undef J9VM_OPT_JAVA_OFFLOAD_SUPPORT
#undef J9VM_OPT_NATIVE_CHARACTER_CONVERTER
#undef J9VM_OPT_NATIVE_LOCALE_SUPPORT
#undef J9VM_OPT_NO_CLASSLOADERS
#undef J9VM_OPT_NRR
#undef J9VM_OPT_PAAS
#undef J9VM_OPT_PACKED
#undef J9VM_OPT_PANAMA
#undef J9VM_OPT_PHP_SUPPORT
#undef J9VM_OPT_SWITCH_STACKS_FOR_SIGNAL_HANDLER
#undef J9VM_OPT_TEMP_NEW_INTERFACE_INVOCATION
#undef J9VM_OPT_USE_OMR_DDR
#undef J9VM_OPT_VALHALLA_VALUE_TYPES
#undef J9VM_OPT_VEE_SUPPORT
#undef J9VM_OPT_ZERO
#undef J9VM_PORT_ZOS_CEEHDLRSUPPORT
#undef J9VM_PROF_COUNT_ARGS_TEMPS
#undef J9VM_PROF_JVMTI
#undef J9VM_RAS_FATAL_ASSERT
#undef J9VM_SIZE_SMALL_CODE
#undef J9VM_SIZE_SMALL_OS_STACK
#undef J9VM_SIZE_SMALL_RAM
#undef J9VM_TEMP_ALIGN_CLASS_SLOT
#undef J9VM_TEMP_KEEP_FLAGS_SLOT
#undef J9VM_THR_EXTRA_CHECKS
#undef J9VM_THR_JLM_HST
#undef J9VM_THR_LOCK_NURSERY_FAT_ARRAYS

#if JAVA_SPEC_VERSION >= 11
#define J9VM_OPT_VALHALLA_NESTMATES
#endif

#ifdef __cplusplus
}
#endif

#endif /* J9CFG_H */
