###############################################################################
# Copyright (c) 2018, 2018 Pavel Samolysov
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
###############################################################################
---
- name: Checkout ibmruntimes
  delegate_to: "openj9-{{ version }}-build"
  git:
    repo: "https://github.com/ibmruntimes/openj9-openjdk-{{ version }}"
    dest: "/root/openj9-openjdk-{{ version }}"
    version: openj9
    update: yes
    force: yes
    accept_hostkey: yes
  tags:
    - build
- name: Set get_source.sh as executable
  delegate_to: "openj9-{{ version }}-build"
  file:
    path: "/root/openj9-openjdk-{{ version }}/get_source.sh"
    mode: 0755
  tags:
    - build
- name: Get the sources
  delegate_to: "openj9-{{ version }}-build"
  shell: "/root/openj9-openjdk-{{ version }}/get_source.sh"
  args:
    chdir: "/root/openj9-openjdk-{{ version }}"
  tags:
    - build
- name: Set configure as executable
  delegate_to: "openj9-{{ version }}-build"
  file:
    path: "/root/openj9-openjdk-{{ version }}/configure"
    mode: 0755
  tags:
    - build
- name: Configure
  delegate_to: "openj9-{{ version }}-build"
  shell: "/root/openj9-openjdk-{{ version }}/configure --with-freemarker-jar=/root/freemarker.jar"
  args:
    chdir: "/root/openj9-openjdk-{{ version }}"
  tags:
    - build
    - compile
- name: Make clean
  delegate_to: "openj9-{{ version }}-build"
  shell: "make clean"
  args:
    chdir: "/root/openj9-openjdk-{{ version }}"
  when: not build.cleanup
  tags:
    - build
    - compile
- name: Make all
  delegate_to: "openj9-{{ version }}-build"
  shell: "make all"
  args:
    chdir: "/root/openj9-openjdk-{{ version }}"
  tags:
    - build
    - compile
- name: Check if j2sdk-image exists
  stat:
    path: "/root/openj9-openjdk-{{ version }}/build/{{ os }}-{{ platform }}-normal-server-release/images/j2sdk-image"
  register: j2sdk
  delegate_to: "openj9-{{ version }}-build"
  tags:
    - build
- name: Create symlink j2sdk to jdk
  file:
    src: "/root/openj9-openjdk-{{ version }}/build/{{ os }}-{{ platform }}-normal-server-release/images/jdk"
    dest: "/root/openj9-openjdk-{{ version }}/build/{{ os }}-{{ platform }}-normal-server-release/images/j2sdk-image"
    state: link
  when: not j2sdk.stat.exists
  delegate_to: "openj9-{{ version }}-build"
  tags:
    - build
- name: Change the owner of the built JDK
  file:
    path: "/root/openj9-openjdk-{{ version }}/build/{{ os }}-{{ platform }}-normal-server-release/images/j2sdk-image/"
    recurse: yes
    owner: "{{ target.user }}"
    group: "{{ target.group }}"
  delegate_to: "openj9-{{ version }}-build"
  tags:
    - build
- name: Remove the previous version of the JDK archive
  file:
    path: "/root/hostdir/openj9-{{ version }}-{{ os }}-{{ platform }}.tar.gz"
    state: absent
  delegate_to: "openj9-{{ version }}-build"
  tags:
    - build
- name: Archive the JDK
  archive:
    path: "/root/openj9-openjdk-{{ version }}/build/{{ os }}-{{ platform }}-normal-server-release/images/j2sdk-image/*"
    dest: "/root/hostdir/openj9-{{ version }}-{{ os }}-{{ platform }}.tar.gz"
    mode: 0644
    owner: "{{ ansible_user.stdout }}"
    group: "{{ ansible_group.stdout }}"
  delegate_to: "openj9-{{ version }}-build"
  tags:
    - build
