/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_cuda_CudaDevice_CacheConfig */

#ifndef _Included_com_ibm_cuda_CudaDevice_CacheConfig
#define _Included_com_ibm_cuda_CudaDevice_CacheConfig
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
