###############################################################################
# Copyright IBM Corp. and others 2021
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] https://openjdk.org/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
###############################################################################/

name: "Remove autoTestPR branch"
on:
  pull_request:
    types: [closed]
jobs:
  rmAutoTestPRBranch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'auto exclude test') && startsWith(github.event.pull_request.head.ref, 'autoTestPR') && (github.event.pull_request.user.login == 'github-actions[bot]')
    steps:
      - name: remove auto test PR branch when the PR is closed
        run: |
          curl -u github-actions:${{ secrets.GITHUB_TOKEN }} -X DELETE ${{ github.event.pull_request.head.repo.url }}/git/refs/heads/${{ github.event.pull_request.head.ref }}